import React from "react";
import LegalTemplate from "./LegalTemplate";
import { AlertTriangle, ShieldAlert, FileText, CheckCircle } from "lucide-react";

export default function DisclaimerPolicy() {
  const content = (
    <div className="space-y-6 text-slate-300 font-sans text-xs sm:text-sm">
      <div className="p-4 bg-amber-500/10 border border-amber-500/30 rounded-xl text-amber-200 font-mono text-xs space-y-2">
        <div className="flex items-center space-x-2 font-bold text-amber-400 uppercase">
          <AlertTriangle className="w-4 h-4 shrink-0" />
          <span>General Liability & Structural Diagnostic Disclaimer</span>
        </div>
        <p className="text-slate-300 leading-relaxed">
          This Disclaimer governs all architectural risk evaluations, subterranean acoustic radar scans, thermal drone imaging, live cost estimates, and pest diagnostic outputs generated by <strong>Aegis BioDefense Pvt. Ltd.</strong> across Delhi NCR.
        </p>
      </div>

      <div className="space-y-4">
        <h3 className="text-sm font-bold text-white font-mono uppercase flex items-center space-x-2 border-b border-white/10 pb-2">
          <FileText className="w-4 h-4 text-emerald-400" />
          <span>1. Diagnostic & Sensor Data Accuracy</span>
        </h3>
        <p>
          Subterranean acoustic radar logs, moisture heatmaps, and AI threat classifications provide high-precision non-invasive structural diagnostics. While our acoustic bio-sensors achieve 99.4% detection accuracy for active subterranean termite galleries (Reticulitermes / Coptotermes species), subterranean soil movement or unmapped concrete encasements may affect deep sub-slab telemetry.
        </p>

        <h3 className="text-sm font-bold text-white font-mono uppercase flex items-center space-x-2 border-b border-white/10 pb-2">
          <ShieldAlert className="w-4 h-4 text-emerald-400" />
          <span>2. Live Calculator & Currency Estimates</span>
        </h3>
        <p>
          Live quote outputs generated in INR (₹), USD ($), AED (د.إ), or GBP (£) represent automated binding quotes based on property square footage and selected defense tier. Final billing remains subject to physical site perimeter verification by an assigned Aegis bio-engineer prior to chemical barrier installation.
        </p>

        <h3 className="text-sm font-bold text-white font-mono uppercase flex items-center space-x-2 border-b border-white/10 pb-2">
          <CheckCircle className="w-4 h-4 text-emerald-400" />
          <span>3. Pre-Existing Structural Damage</span>
        </h3>
        <p>
          Aegis BioDefense treatment shields prevent active pest incursions and subterranean colony expansion. Aegis is not liable for structural timber decay, dry rot, or foundational weakening caused by termite infestations occurring prior to the installation of our Bio-Barrier or Subterranean Radar Shield.
        </p>
      </div>

      <div className="p-4 bg-slate-950 border border-white/10 rounded-xl font-mono text-xs text-slate-400 space-y-1">
        <div className="text-emerald-400 font-bold uppercase">Corporate Headquarters:</div>
        <p className="text-slate-300">Aegis BioDefense Pvt. Ltd. | CEO: Vikash Kumar Roy</p>
        <p>Command Center: 230, D-block, Dwarka Sector 8, Delhi - 110077 | Hotline: +91 93547 31879</p>
      </div>
    </div>
  );

  return (
    <LegalTemplate
      title="Legal & Technical Disclaimer"
      lastUpdated="July 30, 2026"
      content={content}
      subtitle="Structural Diagnostics & Automated Assessment Disclaimer"
      documentId="AEGIS-LEG-DISCL-2026"
      version="2.0.0"
    />
  );
}
